version: "3.0"

services:
  zookeeper:
    container_name: letters_zookeeper
    image: bitnami/zookeeper:3.6
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ALLOW_PLAINTEXT_LISTENER=yes
    networks:
      default_bridge:
        ipv4_address: 192.168.0.10
  kafka:
    container_name: letters_kafka
    image: bitnami/kafka:3.0
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://192.168.0.11:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
#      - KAFKA_CREATE_TOPICS=chat:1:1
    depends_on:
      - zookeeper
    networks:
      default_bridge:
        ipv4_address: 192.168.0.11
  backend:
    container_name: letters_backend
    build: .
    networks:
      default_bridge:
        ipv4_address: 192.168.0.20
  backend2:
    container_name: letters_backend2
    build: .
    networks:
      default_bridge:
        ipv4_address: 192.168.0.21
  nginx:
    container_name: letters_nginx
    build: ./nginx
    ports:
      - "80:80"
    networks:
      default_bridge:
        ipv4_address: 192.168.0.30

networks:
  default_bridge:
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/16