version: "3.0"

# networks:
#   kafka-cluster:
#     driver: bridge

services:
  backend:
    container_name: letters_backend
    build: .
    ports:
      - "8080:8080"
  nginx:
    container_name: letters_nginx
    build: ./nginx
    ports:
      - "80:80"
    environment:
      BACKEND_HOST: ${SERVER_IP}
  zookeeper:
    image: bitnami/zookeeper:latest
    # networks:
    #   - kafka-cluster
    ports:
      - "2181:2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: yes
      ALLOW_PLAINTEXT_LISTENER: yes
  kafka:
    image: bitnami/kafka:latest
    # networks:
    #   - kafka-cluster
    ports:
      - "9092:9092"
    environment:
      # KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: yes
    # volumes:
    #   - /path/to/kafka-persistence:/bitnami/kafka

